### ISSUE TITLE
Remote DJVU file?

### ISSUE THREAD

**Issue by loganjk** [RussCoder/djvujs#1]
Can djvujs view a remote DJVU file, or must the DJVU file be located on the same server as djvujs?  Thank you.

**Comment by RussCoder** [comment]
It doesn't matter where a djvu document is located. DjVu.js runs in the browser and doesn't require any access to the server. So if you can load a file via JavaScript either from any server or from user's computer, the library will process it. In other words, DjVu.js doesn't load a file - it must be loaded by your own. 

If you are asking about indirect multi-page documents, which are stored on the server, then I should tell you, that there are no support in the library for such sort of files on current moment. 

Also, note that the library by no means is completed, and much should be done.

**Comment by loganjk** [comment]
Thank you, this is what I hoped, although some of the files (but not all) are indirect multi-page.  I would like to use this instead of requiring my site's visitors to have a browser plugin to view files from other servers that I currently load in an iframe.  I tested viewing a file on djvujs.net and it worked perfectly.  Then, I copied everything from github and tried to replicate, but it did not work for me -- I could not see the file in the browser after selecting it from my computer.

The console output from my site:

Zero 0  JB2Image.js:49:13
count 1  JB2Image.js:93:13
ONE!!!  JB2Image.js:97:17

The console output from djvujs.net:

Mask decoding time =  79.77500000000055  DjVuPage.js:185:9
Background decoding time =  302.91499999999996  DjVuPage.js:196:9
Foreground decoding time =  46.69000000000051  DjVuPage.js:204:9
DataImage creating time =  59.784999999999854  DjVuPage.js:170:9
1490394452206  DjVuWorker.js:53:17
--** 1490394452207  DjVuWorker.js:59:17
DataURL creating time =  410.130000000001  DjVuViewer.js:151:9
Rescale time =  410.8899999999994  DjVuViewer.js:155:9

In addition to the files from github, I also included yii.js and bootstrap.js that you use on djvujs.net, although I am not sure they are needed for this, but it didn't work either way.

Do you have any ideas of what might be wrong? Thank you.

**Comment by RussCoder** [comment]
It's just because of that I didn't think that someone would like to use the library and added some debug code to master branch and this code broke some of functions (there is an additional thread, a WebWorker, is used, however I debug the library in one thread, so I didn't notice that I broke it)  . Now I removed some of debug code and even fix one small bug, it should work now. Try it out.

**Comment by loganjk** [comment]
Thank you very much for working on the code!  I can now see the DjVu page on my site, which is wonderful, but it looks like the text is inverted (dark text becomes light).  See the image below comparing my site (left) vs. djvujs.net (right):

![djvujs-comparison](https://cloud.githubusercontent.com/assets/13891309/24327340/9f970398-119c-11e7-89fd-81a99dd45376.png)

And about your comment that you "didn't think that someone would like to use the library," I think many people would be interested in your library, actually.  The DjVu browser plugins are not very good, especially for Mac users, and djvujs is the only way I know to view remote DjVu without a plugin.  There are some other projects for viewing DjVu without a plugin, but only if the DjVu is on the same server as the project files.

**Comment by RussCoder** [comment]
One more bug - one more fix. Now should work properly. Thank you for feedback, your remark that the library can be useful inspire me to continue working on it.

**Comment by loganjk** [comment]
Success!  It is working on my server!  Now, I will try to integrate it into my site.  It might take me a few days, but I will let you know how it goes.  **Thank you!**

**Comment by RussCoder** [comment]
You are welcome)

**Comment by loganjk** [comment]
A little update: it is working well for bundled DjVu, but I realize I will need to find a way to make it work for indirect DjVu, too.  As I understand, the index file of an indirect DjVu should contain a list of all the URLs for the separate pages.  Is there any easy way to extract those URLs as text, so I can then use cURL, for example, to get the third URL or the fifth, etc.?

**Comment by loganjk** [comment]
It looks like I can use djvudump to get the file names of the separate pages in an indirect DjVu.  That should work, I will try it.  I would use djvujs to call a proxy on my server that gets the remote indirect DjVu index file, then runs djvudump on it and identifies the file name of the single page I need, then gets that file, which djvujs displays.

**Comment by RussCoder** [comment]
I have never worked with indirect djvu files, and I even don't have one. I suppose it will be good, if you send me such djvu, for exapmple in zip archive. I may figure it out and add some functions to the library. And I didn't understand what do you mean by "djvudump". I suppose it's quite easy to create a function which returns URLs in string format, if it's required.

**Comment by loganjk** [comment]
Here is the index file of an indirect djvu: http://zbc.uz.zgora.pl/Content/3496/directory.djvu

djvudump is part of djvulibre (http://djvu.sourceforge.net/doc/man/djvudump.html).  In Ubuntu, I install with: sudo apt-get install djvulibre-bin.  If you run djvudump on directory.djvu, the output is a list of the .djvu and .djbz file names for all the pages.  If I want the 10th page, I should be able to get the 10th .djvu file listed (and any .djbz it includes, which I can find by running djvudump on it).  The bad news is this takes a few steps, but the good news is I don't have to download the entire large .djvu, I only have to download the small directory.djvu index file and the .djvu for the 10th page, if I only want that one page.

I would prefer to not download anything to my server, but I think I have to because the .djvu is on a different domain that I do not control.  I can't make a cross-domain request for the .djvu in Javascript for security reasons.  So, I use my server as a proxy to get the .djvu file and, then, to djvujs, there is no problem because the .djvu it sees is on my server.

Since I am downloading the file to my server anyway, I could convert it to PDF instead of needing djvujs, but that would use my server's CPU resources instead of the client's.

**Comment by RussCoder** [comment]
Ok, thank you for the reference and explanation. I will try out this sort of djvu.

**Comment by vedro-compota** [comment]
@RussCoder use releases to avoid problems by debug code in master branch: http://fkn.ktu10.com/?q=node/9823
