### ISSUE TITLE
Zoom display optionable

### ISSUE THREAD

**Issue by mb93** [RussCoder/djvujs#14]
Hi RussCoder!
Thank your for your plugin.
I have a new request: Would it be possible to have for the zoom percentage , an option at initialization (like rotation) to choose it, for example: {zoom: xxx} or xxx=percent (50,100,150,200,etc.) ?
I have many cases where I often have to enlarge the zoom to 150~200 to have a usable display. It would be a great help.
Thank you.

**Comment by RussCoder** [comment]
Hello! Yes, if you just want an additional parameter to set the scale programmatically, I can add it rather easily. I will notify you here when it's done.

**Comment by mb93** [comment]
Many thanks, you are awesome!

**Comment by RussCoder** [comment]
Hello! 

I have added a `pageScale` option - it's a number from 0.1 to 6, and used in the same manner as `pageRotation`.  I have added a description of it here too: https://djvu.js.org/downloads

You may try it out now.

**Comment by mb93** [comment]
Hi !
It works very well,  thank you !
Very much appreciated.
