### ISSUE TITLE
feature_request(encoding): decode URL symbols before saving

### ISSUE THREAD

**Issue by Kristinita** [RussCoder/djvujs#21]
### 1. Summary

It would be nice, if DjVu.js will decode URL symbols from filename before file saving.

### 2. Steps to reproduce

I open the link **<http://93.174.95.29/main/1852000/0e2bb368201041ee576c34aba7d83347/%D0%91%D1%8D%D1%80%D0%BE%D0%BD%20%D0%A0.%2C%20%D0%9A%D0%B5%D1%80%D1%80%20%D0%9D.%2C%20%D0%9C%D0%B8%D0%BB%D0%BB%D0%B5%D1%80%20%D0%9D.%20-%20%D0%A1%D0%BE%D1%86%D0%B8%D0%B0%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F%20%D0%BF%D1%81%D0%B8%D1%85%D0%BE%D0%BB%D0%BE%D0%B3%D0%B8%D1%8F%20%D0%B3%D1%80%D1%83%D0%BF%D0%BF%D1%8B_%20%D0%BF%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81%D1%8B%2C%20%D1%80%D0%B5%D1%88%D0%B5%D0%BD%D0%B8%D1%8F%2C%20%D0%B4%D0%B5%D0%B9%D1%81%D1%82%D0%B2%D0%B8%D1%8F.djvu>** in Firefox with DjVu.js → I click to `Save` → I look filename of downloaded file.

### 3. Expected behavior

`Бэрон Р., Керр Н., Миллер Н. - Социальная психология группы_ процессы, решения, действия.djvu`

### 4. Actual behavior

`%D0%91%D1%8D%D1%80%D0%BE%D0%BD%20%D0%A0.%2C%20%D0%9A%D0%B5%D1%80%D1%80%20%D0%9D.%2C%20%D0%9C%D0%B8%D0%BB%D0%BB%D0%B5%D1%80%20%D0%9D.%20-%20%D0%A1%D0%BE%D1%86%D0%B8%D0%B0%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F%20%D0%BF%D1%81%D0%B8%D1%85%.djvu`

### 5. Notes

You can have problems with link above.

1. If you in Russian Federation, [**АнтиЗапрет**](https://antizapret.prostovpn.org/) or its alternatives may be required.
1. Direct link may be changed; actual links for this book you can find [**here**](http://libgen.is/book/index.php?md5=0E2BB368201041EE576C34ABA7D83347).

Thanks.

**Comment by RussCoder** [comment]
Now it fixed in the extension v0.3.5.0.
Already available for Firefox, for Chrome will be available after their review process which may take a couple of weeks.

**Comment by Kristinita** [comment]
**Status: Confirmed** ✔

I downloaded [**this**](http://libgen.is/book/index.php?md5=7C89946E1E7190D91DCEBB6399D26255) and [**this**](http://libgen.is/book/index.php?md5=750C708E2E09D500AF315232BAF74BBB) books via DjVu.js → files names is normal.

We're waiting **#15** and **#22**.

Thanks.
