### ISSUE TITLE
feature_request(sites): LibGen/Z-Library support

### ISSUE THREAD

**Issue by Kristinita** [RussCoder/djvujs#22]
### 1. Summary

It would be nice, if DjVu.js will open remote DjVu files from [**LibGen**](http://libgen.is/) and [**Z-Library**](https://z-lib.org/) like [**PDF.js**](https://mozilla.github.io/pdf.js/) opens PDF's from this resources.

### 2. Note

If you in Russian Federation, [**АнтиЗапрет**](https://antizapret.prostovpn.org/) or its alternatives may be required for opening links from this issue.

### 3. Argumentation

Z-Library is the world largest free ebook library. Nowadays (24.11.2019) it contains 4891894 books. Most of thousand books from [**my collection**](https://kristinita.netlify.com/special/%D0%BF%D0%BE%D0%BB%D0%BD%D0%B0%D1%8F-%D0%B1%D0%B8%D0%B1%D0%BB%D0%B8%D0%BE%D0%B3%D1%80%D0%B0%D1%84%D0%B8%D1%8F) I was getting from Z-Library. Also, use LibGen search, I can find books in similar big libraries — LibGen, Lib.rus.ec and [**BookFI**](http://en.bookfi.net/).

For details, you can read [**my instruction about getting free ebooks**](https://kristinita.netlify.com/erics-rooms/%D0%B3%D1%80%D0%B5%D0%B9%D0%B7%D0%B8-%D1%84%D0%B0#%D0%9F%D0%BE%D0%B8%D1%81%D0%BA-%D0%BB%D0%B8%D1%82%D0%B5%D1%80%D0%B0%D1%82%D1%83%D1%80%D1%8B) (in Russian).

### 4. Steps to reproduce

For example, I want to read Nikolay Zelenevsky's book about dogs anatomy.

I make [**search request to LibGen**](http://libgen.is/search.php?req=%D0%97%D0%B5%D0%BB%D0%B5%D0%BD%D0%B5%D0%B2%D1%81%D0%BA%D0%B8%D0%B9+%D0%90%D0%BD%D0%B0%D1%82%D0%BE%D0%BC%D0%B8%D1%8F+%D1%81%D0%BE%D0%B1%D0%B0%D0%BA%D0%B8) → I click, for example, to number `4`:

![Number 4](https://i.imgur.com/KE8HRyZ.png)

`Get links` → I click to, for example, `https://openlib.xyz` → `get item`.

1. Expected behavior — I clicked to PDF link (see image above)
1. Unexpected behavior — to DjVu link

### 5. Expected behavior

PDF.js (by default in Firefox):

![PDF.js](https://i.imgur.com/JfCsNjW.png)

File successfully opened in browser. Direct links to specific pages as **<https://d-m.freelib.xyz/get_item/5c63f84150b42539789d0624#page=14>** also works.

### 6. Unexpected behavior

DjVu.js, option `Open all .djvu links via the viewer` is activated:

![DjVu.js](https://i.imgur.com/dupBhWE.png)

File doesn't open in DjVu.js Viewer.

Thanks.

**Comment by RussCoder** [comment]
@Kristinita @r-pankevicius

In the version 0.3.6.0 (already available for Firefox, will be available for Chrome after the review) I have added the support of http headers analysis for djvu detection. It's enabled via a corresponding option on the initial screen of the viewer.
 
I process 3 cases:
- `Content-Type: image/x.djvu`
- `Content-Type: image/vnd.djvu`
- `Content-Disposition: attachment; filename="SomeName.djvu"` or `Content-Disposition: inline; filename="SomeName.djvu"`

The last one is needed for some sites which do not add the `Content-Type` headers. However there are other forms of `Content-Disposition` and they are not covered. If you find a site where it doesn't work, create a new issue.
