### ISSUE TITLE
Feature request: don't ignore the parameters.

### ISSUE THREAD

**Issue by jsbien** [RussCoder/djvujs#26]
The search engine https://szukajwslownikach.uw.edu.pl/ uses links in the form 
`https://szukajwslownikach.uw.edu.pl/redirect/ueHdq/http/djvu.szukajwslownikach.uw.edu.pl/linde/index.djvu%3Fdjvuopts&page=1&zoom=width&showposition=0.187,0.054&highlight=408,2979,73,88`
(the redirection was intended for gathering statistics). Your viewer is ignoring the parameters and open always the very first page.

I mean the Firefox extension. The relation to the closed issue #25 is not clear for me.

**Comment by RussCoder** [comment]
Well, it won't be a problem to process the page number parameter. As for the others, I will think. Most of them are rather hard to implement (cause there is just no such functionality in the viewer now like highlighting an area on the page) and I doubt the game is worth the candle. But the page number may be supported easily.

**Comment by jsbien** [comment]
Thanks for your quick answer. I suspected that highlighting can be difficult, just handling the page number will be a great step forward - for the time being to use the full power of the search engine the user has to install the dedicated program (https://bitbucket.org/mrudolf/djview-poliqarp/).

**Comment by RussCoder** [comment]
In the version 0.3.6.0 (already available for Firefox, will be available for Chrome after the review), the page number parameter is processed. Check it out.

**Comment by jsbien** [comment]
Thanks, it works.

**Comment by jsbien** [comment]
Today we notice
