### ISSUE TITLE
Save unbundled document correctly (or at least issue a warning)

### ISSUE THREAD

**Issue by jsbien** [RussCoder/djvujs#27]
"Save" saves only the index file. You can test it e.g. on https://djvu.szukajwslownikach.uw.edu.pl/sgkp/01/index.djvu and https://djvu.szukajwslownikach.uw.edu.pl/linde-t/01/index.djvu.

**Comment by RussCoder** [comment]
This feature may be worth implementing. I think you want to bundle an indirect djvu into one file? It should not be too hard, since there is already some code for creating djvu files in the library, however it will take time to reread the specification and to code the new feature.

**Comment by jsbien** [comment]
Please do it the easiest way. Perhaps the code of djvu-wget (https://github.com/jwilk-archive/djvu-toolbox) can be of some help.

**Comment by RussCoder** [comment]
I have implemented the feature in the version 0.5.2.0 of the extension. 
Already available for Firefox, will be available for Chrome within several days. 

When you try to save an indirect djvu there will be a dialog with two options.
Try it out.

**Comment by jsbien** [comment]
It works, thanks.
