### ISSUE TITLE
The task contains an incorrect sequence of functions!

### ISSUE THREAD

**Issue by jsbien** [RussCoder/djvujs#29]
We get this error message e.g. for
https://djvu.szukajwslownikach.uw.edu.pl/sw/01/index.djvu?djvuopts&page=1&zoom=width&showposition=0.493,0.115&highlight=782,3470,1261,200
Other similar links work correctly, e.g.
https://djvu.szukajwslownikach.uw.edu.pl/linde/index.djvu?djvuopts&page=1&zoom=width&showposition=0.187,0.054&highlight=408,2979,73,88
https://djvu.szukajwslownikach.uw.edu.pl/linde-t/01/index.djvu?djvuopts&page=1&zoom=width&showposition=0.376,0.419&highlight=1423,3761,1141,218
The failing link is opened correctly by djview.

**Comment by jsbien** [comment]
Looks like you don't handle shared dictionary 'shared_anno.iff'.

**Comment by RussCoder** [comment]
Yes, it seems that there is a peculiarity in that document, which I haven't taken into account when implemented the support of indirect djvu. I will debug it more thoroughly.

But how did you understand that the problem is in 'shared_anno.iff' ? Did you debug the code? Just interesting to know.

**Comment by jsbien** [comment]
When a document is opened in djview the View menu has "Information" entry which lists all the "chunks" of the document. All other dictionaries on our site, which are opened correctly, don't contain the 'shared_anno.iff' chunk.

**Comment by RussCoder** [comment]
It turned out the shared_anno.iff is essentially empty - only 16 bytes of headers. Didn't expected there maybe useless empty dependencies. But formally, it's a valid djvu. Just ignored the empty chunk and it worked.
Available for Firefox, submitted to Chrome.
Version 0.3.6.1
