### ISSUE TITLE
A radically different approach?

### ISSUE THREAD

**Issue by jsbien** [RussCoder/djvujs#35]
The purpose of your very useful extension can be perhaps achieved quite differently:
https://sourceforge.net/p/djvu/feature-requests/100/
Do you think writing such an extension would be difficult? Modifying djview4 is another separate problem.

**Comment by RussCoder** [comment]
I do not quite understand what the different approach do you speak about? I have read the feature request by the link, but it didn't get clearer for me. Elaborate more, please.

**Comment by jsbien** [comment]
Edit in Emacs extension to Firefox and Chrome show that an extension can pass toa appropriately modified programt some information from the browser. So the idea is to make and extension which pass to djview4 the address and other parameters found on the webside. I'm not sure the extension can start a program, perhaps djview has to be running already in the server mode, but this is not a problem from a user point of view (I don't know what exactly has to be changed in djview and how difficult it is, but as I said this is another problem).

**Comment by RussCoder** [comment]
I do not know about starting a native program, but web extensions can definitely interact with native programs installed locally. So theoretically it should be possible to create such an extension. But it's has nothing in common with DjVu.js Viewer, and should be considered as an additional feature of djvu4, so you are right that you created a feature request there.
