### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by verglor** [RussCoder/djvujs#36]
> So if you want to use the library and need the documentation, create an issue on GitHub

Could you provide  `profound and intelligible documentation, describing API of the DjVu.js library and the viewer`, please ?

**Comment by RussCoder** [comment]
Hello! As for the viewer's documentation it's completely written here https://djvu.js.org/downloads
There are not too many methods available for the programmatic usage. 

As for the library, I will try to satisfy your request within several days.
I will notify you here once I did it.

**Comment by RussCoder** [comment]
Here it is https://github.com/RussCoder/djvujs/blob/master/library/API.md

**Comment by verglor** [comment]
Thank You!
