### ISSUE TITLE
Fullscreen mode

### ISSUE THREAD

**Issue by verglor** [RussCoder/djvujs#37]
Could you please implement fullscreen reading mode in viewer ?
Difference to "full page mode" would be:

- switching to fullscreen with [Fullscreen API](https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API)
- hiding all controls (mainly contents panel and bottom bar with filename)
- optionally slimmed navigation menu could be displayed, but should also be hiddable
- gesture navigation would be great (otherwise automatic switching to continuous scroll mode + grab cursor mode would be necessary if navigation menu is hidden)
 
It should be possible to toggle fullscreen mode or individual panels with buttons on navigation menu and also programatically by `config` object.

**Comment by RussCoder** [comment]
What is the point in the real full screen mode? If the user wants to switch to the full screen mode he can press F11 by himself. Even built-on pdf viewers of browsers aren't in full-screen mode by default. They behave as other pages. 

As for the other points you listed, I have similar plans. 
By the way, did you notice that the left panel can be narrowed manually? I have recently change design a bit, but the cursor changes when you hover it over the border. 

I'm going to redesign it again and just make both, left and bottom panels, auto-hiddable, add an option to pin/unpin them, and automatically show them if cursor hovers over the corresponding areas and they are unpinned. But I'm not sure when I will do it.

**Comment by RussCoder** [comment]
What is the point in the real full screen mode? If the user wants to switch to the full screen mode he can press F11 by himself. Even built-in pdf viewers in browsers aren't in full-screen mode by default. They behave as other pages.

As for the other points you listed, I have similar plans.
By the way, did you notice that the left panel can be narrowed manually? I have recently changed the design a bit and it may become unobvious, but the cursor still changes when you hover it over the border.

I'm going to redesign it again and just make both panels, left and bottom, auto-hiddable, add an option to pin/unpin them, and automatically show them if cursor hovers over the corresponding areas and they are unpinned. But I'm not sure when I will do it.

**Comment by verglor** [comment]
Not all browsers has built-in fullscreen switch (mainly mobile). I didn't suggest to make it default though - just to have the button to toggle fullscreen and hide controls in one click (or touch).

I really like [pdf.js viewer](https://mozilla.github.io/pdf.js/web/viewer.html) and it's "Switch to Presentation Mode" which uses whole screen for content:
![pdf.js viewer navigation bar](https://i.imgur.com/Oj01lMv.png)
It is used in [calibre-web](https://github.com/janeczku/calibre-web) for reading PDFs in browser.

I would like to integrate djvu.js into calibre-web to be able to [read djvu in browser](https://github.com/janeczku/calibre-web/pull/1713) too.

**Comment by RussCoder** [comment]
Yes, I see the point. A normal mobile version is needed. Now there is no mobile version at all.

**Comment by r-pankevicius** [comment]
@verglor Do you have a link to the public calibre-web running online?

**Comment by r-pankevicius** [comment]
@RussCoder It took for me half a year to find out that "the left panel can be narrowed manually".

Maybe you can put some "I've seen it many times and I know how to use it" UI improvement?

Like 3 vertical dashes in the middle.

**Comment by r-pankevicius** [comment]
@verglor **If you use** djvujs in calibre-web would you mind to update your license?

If you use GPL 3.0, then it's not compatible with [djvujs license](https://github.com/RussCoder/djvujs/blob/master/LICENSE).

Even Linux Kernel uses GPL 2.0 license and do not plan to switch to 3.0. (That's long story, I'll not go deeper into it).

I'm not fanatic of license wars, but it would be good if you will explicitly state that "this portion is under GPL 3.0 license" and "that portion is under that license".

**Comment by r-pankevicius** [comment]
Hmmm, it looks like Unlicense is GPL - compatible indeed.
https://www.gnu.org/licenses/license-list.en.html#Unlicense

That requires deeper investigation...

**Comment by RussCoder** [comment]
@r-pankevicius I have added a visual handle to the left panel in the viewer 0.5.6

**Comment by r-pankevicius** [comment]
Yes, I see, thanks.

**Comment by verglor** [comment]
Hi @r-pankevicius,
> 
> 
> Do you have a link to the public calibre-web running online?

I do not. But you can easily run it by yourself in docker: [linuxserver/calibre-web](https://hub.docker.com/r/linuxserver/calibre-web)


> 
> 
> **If you use** djvujs in calibre-web would you mind to update your license?

Sorry, I am not the author of calibre-web.

**Comment by RussCoder** [comment]
I have added full-screen mode in the version `0.8.0`.
But I haven't added a corresponding programmatic API.
@verglor do you really need such an API? Or it's required just in case?

**Comment by RussCoder** [comment]
Reopen the issue, id needed.
