### ISSUE TITLE
Wrong tooltip for previous/next buttons in DjVu.s Viewer

### ISSUE THREAD

**Issue by aamodio** [RussCoder/djvujs#48]
Hi,
the tooltip displayed over the previous/next buttons is wrong. It is displayed the go to page one. Tested in Chrome 88.0.4324.96 and In Safari 14.0.2 

Thanks,
A.

**Comment by RussCoder** [comment]
Hello!

The tooltip is "Click on the number to enter it manually".
Why do you find it wrong?

**Comment by aamodio** [comment]
<img width="1086" alt="wronglabel" src="https://user-images.githubusercontent.com/4546909/107798771-e1f0b700-6d5c-11eb-9819-9de2bdd7e743.png">

Hello,
When I move the mouse over prev/next buttons I see the wrong label (see attach file, sorry the cursor was not capture but I assure that is over the next page button). It seams the page chooser box is drawn over the other two left/right buttons.

Thanks,
A.

**Comment by RussCoder** [comment]
It's intentional. I think everybody can understand what previous and next buttons do without tooltips, but it may be unobvious that the page number can be edited manually, because it's not an input field by default.

**Comment by aamodio** [comment]
Ok, but I was mislead by the presence of prev/next tooltips in translation. I still think that the tooltip for manually page selector must be shown only over the appropriate button.

Thanks,
A.
