### ISSUE TITLE
Feature request: hide Contents via configure/constructor

### ISSUE THREAD

**Issue by r-pankevicius** [RussCoder/djvujs#49]
I work with library where most often first page is a map followed by documents, and contents of DjVu document almost always contains 2 links: map and document.

Not only it is quite useless to have content visible but also it takes screen space when looking at map.

I'd like to have setting to turn Contents off and to use more screen space for the document.

**Comment by RussCoder** [comment]
I have added a new UI option `showContentsAutomatically` in the v0.5.5. You need to set it to `false`.
It described here https://djvu.js.org/downloads
