### ISSUE TITLE
Feature request: A confirmation message when saving the document

### ISSUE THREAD

**Issue by r-pankevicius** [RussCoder/djvujs#51]
I work with the library (actually libraries) where users have to log in and access to DjVu documents is controlled by the authorization. To put it simply, users pay for the access to these documents and my company doesn't want them to be freely shared.

Examples in the public world: youtube and vimeo doesn't allow you to save their videos. You can watch them at their platform, but not download or share.

So I'd like to show a message to the users downloading (pressing Save) the document reminding them a small portion of the license agreement (e.g. for personal use, but not for public sharing) ("Yes, I agree" is enough) .

**Comment by RussCoder** [comment]
It can be done. Although, there are different ways how it can be implemented. I will think about it.

**Comment by r-pankevicius** [comment]
I haven't seen it in action, but as I remember (from translation strings) there is a message "what you would like to do with this **multipart** document: save this part or pack all parts and save a whole document.

Maybe like this?

**Comment by RussCoder** [comment]
Yes. But I meant a different thing. I could just accept a callback, returning `true`/`false`, in which you could just use a standard `confirm()` function. Or to accept a text, which is shown in a dialog inside the viewer. Probably, the latter variant.

**Comment by r-pankevicius** [comment]
I was thinking more about a data-driven stuff like this:
undefined = default (as it is now);
string  = the message to display with OK button;
2 strings array:   the message to display + text in the button ("Yes,  I agree").

Your idea about callback function returning true/false is maybe OK, but I don't fully understand how it will fit here.

Maybe you can give an example of callback function that will work fine for my initial feature request?

**Comment by RussCoder** [comment]
The example of such a function: 
```js
function confirmation() {
   return confirm("Doing this you agree with that");
}
```

Of course, in a more general case it should return a `Promise` resolving to `true` or `false` in order to allow you to use something else besides the `confirm()` blocking function. 
The idea to use a callback came to me with a desire not to create additional visual component and do as little as possible. 
However, I know that without `confirm()` creation of custom window will be a hassle for you, much greater than to add such a feature using existing viewer components for me.

**Comment by r-pankevicius** [comment]
Maybe:

```javascript
function confirmation(confirm) {
   return confirm("Doing this you agree with that");
}
```

**Comment by r-pankevicius** [comment]
Or more sophisticated:

```javascript
function confirmation(confirm) {
   return confirm(
        /*message*/"Doing this you agree with that", 
        {
            "ok" : "Yes, I agree",
             "cancel": "No, I disagree",
             "default" : "ok"
         });
}

```

**Comment by RussCoder** [comment]
Do you know that `confirm()` is a browser built-in function? You can run `confirm('Hello!')` in the console right now. 

In the latest release (viewer 0.5.6), I added a new UI option for you: 

```json5
uiOptions: {
    onSaveNotification: {
      text: "Here is your notification/agreement for the user",
      yesButton: "Text on the yes button", // optional
      noButton: "Text on the no button", // optional
    },
}
```

It's also described in the documentation on the website.

**Comment by r-pankevicius** [comment]
If you see browser's confirm you'll feel like today is year 1999.
