### ISSUE TITLE
Disable "Print" button via config switch

### ISSUE THREAD

**Issue by r-pankevicius** [RussCoder/djvujs#66]
I played with new print functionality. Impressive! But I found that it's often is hell slow and doesn't render our typical documents correctly.

So I'd like to have config switch to disable print button for now till I'll be more confident with the feature.

I will send you examples of my documents later by mail.

**Comment by RussCoder** [comment]
I will do it.
Yes, examples of such documents would be useful.

**Comment by RussCoder** [comment]
I have added the UI option `hidePrintButton` in the viewer v.0.6.0. It's described on the website.
