### ISSUE TITLE
Print function doesn't work with Safari

### ISSUE THREAD

**Issue by aamodio** [RussCoder/djvujs#68]
Hi RussCoder,

the new print function (Viewer v.0.6.0 - Lib v.0.5.3) doesn't work with Safari 14.0.3 (16610.4.3.1.4)  under Mac Os Big Sur (11.2.2 (20D80)). The preview window, printed page as PDF export are blank (tested also with only one page rendered).
It works instead under Chrome on same OS.

Tested with this installation: https://tinyurl.com/jcwtxnws
<img width="1208" alt="print_doesnt_work" src="https://user-images.githubusercontent.com/4546909/110752297-6132b700-8245-11eb-83a2-fc8ea5a77678.png">

**Comment by RussCoder** [comment]
Hello! Yes, I see. I will release a fix soon.

**Comment by RussCoder** [comment]
This issue is fixed in the viewer v.0.6.1
