### ISSUE TITLE
Failed at the DjVu.js@ start script 'node server.js'

### ISSUE THREAD

**Issue by petrakovich-g-n** [RussCoder/djvujs#7]
Получаю ошибку такого плана при выполнении команды: npm run start
Failed at the DjVu.js@ start script 'node server.js'

npm-debug log:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'start' ]
2 info using npm@3.5.2
3 info using node@v4.2.6
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle DjVu.js@~prestart: DjVu.js@
6 silly lifecycle DjVu.js@~prestart: no script for prestart, continuing
7 info lifecycle DjVu.js@~start: DjVu.js@
8 verbose lifecycle DjVu.js@~start: unsafe-perm in lifecycle true
9 verbose lifecycle DjVu.js@~start: PATH: /usr/share/npm/bin/node-gyp-bin:/var/www/doctor4891/data/www/freedocs.xyz/djvujs-master/library/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
10 verbose lifecycle DjVu.js@~start: CWD: /var/www/doctor4891/data/www/freedocs.xyz/djvujs-master/library
11 silly lifecycle DjVu.js@~start: Args: [ '-c', 'node server.js' ]
12 info lifecycle DjVu.js@~start: Failed to exec start script
13 verbose stack Error: DjVu.js@ start: `node server.js`
13 verbose stack spawn ENOENT
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:17:16)
13 verbose stack     at emitTwo (events.js:87:13)
13 verbose stack     at ChildProcess.emit (events.js:172:7)
13 verbose stack     at maybeClose (internal/child_process.js:821:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid DjVu.js@
15 verbose cwd /var/www/doctor4891/data/www/freedocs.xyz/djvujs-master/library
16 error Linux 4.4.0-112-generic
17 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "start"
18 error node v4.2.6
19 error npm  v3.5.2
20 error file sh
21 error code ELIFECYCLE
22 error errno ENOENT
23 error syscall spawn
24 error DjVu.js@ start: `node server.js`
24 error spawn ENOENT
25 error Failed at the DjVu.js@ start script 'node server.js'.
25 error Make sure you have the latest version of node.js and npm installed.
25 error If you do, this is most likely a problem with the DjVu.js package,
25 error not with npm itself.
25 error Tell the author that this fails on your system:
25 error     node server.js
25 error You can get information on how to open an issue for this project with:
25 error     npm bugs DjVu.js
25 error Or if that isn't available, you can get their info via:
25 error     npm owner ls DjVu.js
25 error There is likely additional logging output above.
26 verbose exit [ 1, true ]

**Comment by RussCoder** [comment]
Да и я обновил документацию, теперь все должно быть понятнее.
