### ISSUE TITLE
About  Djvu picture size is  2-3M   can't preview  in Firefox browser

### ISSUE THREAD

**Issue by beijinghxt** [RussCoder/djvujs#75]
a djvu picture with  2-3M size  can't loading  in Firefox browser.  The following is the error message：
   Exception { name: "NS_ERROR_FAILURE", message: "", result: 2147500037, filename: "file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js", lineNumber: 2, columnNumber: 0, data: null, stack: "logarithmicScale@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:2:333643\ndrawImageOnCanvas@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:2:333961\nupdateImageIfRequired@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:2:333281\ncomponentDidMount@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:2:332815\nhl@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:2:163891\nNs@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:2:180826\nt.unstable_runWithPriority@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:2:200219\nVo@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:2:122578\njs@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:2:177563\ngs@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:2:173647\nYo/<@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:2:122801\nt.unstable_runWithPriority@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:2:200219\nVo@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:2:122578\nYo@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:2:122748\nGo@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:2:122681\nvs@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:2:173743\nnotify@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:2:241179\nm</t.notifyNestedSubs@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:2:241814\nm</t.handleChangeWrapper@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:2:241882\nd@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:2:248907\nwi/this.eventMiddleware/</<@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9:36732\nc/</<@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9:15195\nfo/</</<@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9:2267\ndispatch@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:2:250703\nQo/<@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9:4201\nza.PUT/<@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9:8286\nxa@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9:6222\nOa@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9:6430\n_a@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9:6276\nza.PUT@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9:8241\nXa/l<@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9:12866\nd@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9:13784\nf@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9:13296\ns@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9:13569\npromise callback*Ma@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9:7825\nXa/l<@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9:12787\nd@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9:13784\nf@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9:13296\ns@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9:13569\nza.SELECT@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9:10243\nXa/l<@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9:12866\nd@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9:13784\nf@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9:13296\ns@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9:13569\nza.SELECT@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9:10243\nXa/l<@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9:12866\nd@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9:13784\nf@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9:13296\nXa@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9:13061\nza.FORK/<@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9:9654\nka@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9:6313\nza.FORK@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9:9633\nXa/l<@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9:12866\nd@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9:13784\nf@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9:13296\ns@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9:13569\nl@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9:8086\nDa/e</e.put@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9:7569\nDa/e.put@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9:7743\nc/</<@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9:15208\nfo/</</<@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9:2267\ndispatch@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:2:250703\nQo/<@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9:4201\nza.PUT/<@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9:8286\nxa@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9:6222\nOa@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9:6430\n_a@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9:6276\nza.PUT@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9:8241\nXa/l<@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9:12866\nd@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9:13784\nf@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9:13296\ns@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9:13569\npromise callback*Ma@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9:7825\nXa/l<@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9:12787\nd@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9:13784\nf@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9:13296\ns@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9:13569\nza.SELECT@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9:10243\nXa/l<@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9:12866\nd@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9:13784\nf@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9:13296\ns@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9:13569\nza.PUT/<@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9:8336\nxa@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9:6222\nOa@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9:6430\n_a@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9:6276\nza.PUT@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9:8241\nXa/l<@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9:12866\nd@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9:13784\nf@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9:13296\ns@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9:13569\npromise callback*Ma@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9:7825\nXa/l<@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9:12787\nd@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9:13784\nf@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9:13296\ns@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9:13569\npromise callback*Ma@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9:7825\nXa/l<@file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9:12787\n" }
djvu_viewer_0.5.1.js:2:160391
    ll file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:2
    callback file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:2
    da file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:2
    hl file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:2
    Ns file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:2
    unstable_runWithPriority file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:2
    Vo file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:2
    js file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:2
    gs file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:2
    Yo file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:2
    unstable_runWithPriority file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:2
    Vo file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:2
    Yo file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:2
    Go file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:2
    vs file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:2
    notify file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:2
    notifyNestedSubs file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:2
    handleChangeWrapper file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:2
    d file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:2
    eventMiddleware file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    c file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    fo file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    dispatch file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:2
    Qo file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    PUT file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    xa file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    Oa file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    _a file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    PUT file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    l file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    d file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    f file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    s file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    (异步：promise callback)
    Ma file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    l file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    d file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    f file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    s file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    SELECT file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    l file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    d file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    f file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    s file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    SELECT file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    l file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    d file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    f file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    Xa file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    FORK file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    ka file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    FORK file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    l file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    d file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    f file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    s file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    l file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    put file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    put file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    c file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    fo file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    dispatch file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:2
    Qo file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    PUT file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    xa file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    Oa file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    _a file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    PUT file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    l file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    d file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    f file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    s file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    (异步：promise callback)
    Ma file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    l file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    d file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    f file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    s file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    SELECT file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    l file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    d file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    f file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    s file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    PUT file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    xa file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    Oa file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    _a file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    PUT file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    l file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    d file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    f file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    s file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    (异步：promise callback)
    Ma file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    l file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    d file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    f file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    s file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    (异步：promise callback)
    Ma file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    l file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    d file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    f file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    Xa file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    FORK file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    ka file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    FORK file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    l file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    d file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    f file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    s file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    l file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    put file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    put file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    xa file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    Oa file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    _a file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    put file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    c file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    fo file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:9
    z file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:2
    onload file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:2
    (异步：EventHandlerNonNull)
    processFile file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:2
    onChange file:///C:/Users/zbwt/Desktop/djvu/djvu_viewer_0.5.1.js:2

**Comment by RussCoder** [comment]
Can you give me the file please? You can send it at `djvujs@yandex.ru` or pack it into a `zip` archive and attach here.

**Comment by beijinghxt** [comment]
> Can you give me the file please? You can send it at `djvujs@yandex.ru` or pack it into a `zip` archive and attach here.
[sample.zip](https://github.com/RussCoder/djvujs/files/7189472/sample.zip)

**Comment by RussCoder** [comment]
Thanks. I confirm that the problem exists in Firefox in the single page mode, when the image is drawn on the canvas. In case of the continuous scroll mode, when the image is converted into PNG, it works (you can switch to another mode using any other document, and then the preference will be remembered). 

I'm not sure whether I will be able to fix it, since 16800 * 12600 is quite a big image. And the error is browser-specific. But I will keep you updated.

**Comment by beijinghxt** [comment]
![code](https://user-images.githubusercontent.com/26615734/134288555-a2147967-d06d-4721-8d55-4fdee04ecad8.png)

@RussCoder ,thanks.Can you tell me how to set the continuous scroll mode is the default mode

**Comment by RussCoder** [comment]
Right now there is no API to change view modes. But I can add an option. 
As for the first problem, I found a solution, not too robust, but images up to 20 000 * 20 000 can be supported. 
I will try to make a release soon.

**Comment by beijinghxt** [comment]
@RussCoder,I found  a link  about djvu-previewer [https://github.com/mateusz-matela/djvu-html5](url), this performance is better ,
It has nothing to do with the size of the picture。But it has no rotation function.

**Comment by RussCoder** [comment]
You are free to choose any solution you like :)

**Comment by beijinghxt** [comment]
sure, I just want you to know the code whether or not can be used as a reference for you to improve your code. Thank you for your reply！

**Comment by RussCoder** [comment]
I have released a new version. Now the single page mode works for you file. You can download it from the website or latest release. The API to change the view mode was added. Read the docs on the website.

**Comment by r-pankevicius** [comment]
@beijinghxt https://github.com/mateusz-matela/djvu-html5 is unfortunately not supported. 2 years ago I could not even compile it, because of incompatibility with newer GWT version. Yet, GWT is dead (latest stable release is 2.9.0 / May 2, 2020; 16 months ago).
