### ISSUE TITLE
Odd/Even page spreads

### ISSUE THREAD

**Issue by jackdyson31** [RussCoder/djvujs#80]
Thank you for this great tool for in-browser reading of djvu files!

Just a quick suggestion:

It would be good to have an "open book" page spread viewing capability which is very useful for viewing publications with multiple pages displayed on large screens.

Thank you very much indeed for all your hard work.

**Comment by RussCoder** [comment]
Hello! 
Thanks for the feedback.
Yes, it can be done. I have taken it into account.

**Comment by jackdyson31** [comment]
Thanks a lot RussCoder ! Feedback very much appreciated ))
Best!

**Comment by jackdyson31** [comment]
Hello RC,

Just following up - any progress on this ?

Regards,

Jack

**Comment by RussCoder** [comment]
Well, I started to work on it yesterday. Maybe I will release it within 2 weeks.

**Comment by jackdyson31** [comment]
Hello there,

Thankyou very much indeed RussCoder. I really appreciate the effort. I'll recommend the plugin to as many people as I can.

Kind regards,

Jack

**Comment by RussCoder** [comment]
I released the new feature. I implemented the user interface in an unusual, but, to my mind, more powerful way. You can try it out on the website https://djvu.js.org/
As for the browser extensions - they are being reviewed. So they will be updated in a while (up to several weeks in case of Chrome).

**Comment by RussCoder** [comment]
Hello Jack!
I released the new feature. I implemented the user interface in an unusual, but, to my mind, more powerful way. You can try it out on the website https://djvu.js.org/
As for the browser extensions - they are being reviewed. So they will be updated in a while (up to several weeks in case of Chrome).

**Comment by jackdyson31** [comment]
Hello Russcoder,

Sorry for the late reply ! The new interface looks very good indeed -especially the contents.
One question - how do I activate the "double page" or "page spread" feature ?

**Comment by RussCoder** [comment]
Maybe you used an outdated version, but I the only thing I added to the interface in the version 0.9.0 is two number fields near the continuous scroll mode button (when it's enabled). They are available only in the full version (in the mobile version they are hidden). Tooltips will explain you what those numbers mean - the number of pages in a row and the number of pages in the first row.

**Comment by RussCoder** [comment]
I don't want to rename it. It's called "Continuous scroll view mode", and it is good enough. And the name is mentioned only in the button tooltip. 
It is already available both in Firefox and Chrome.

**Comment by jackdyson31** [comment]
Hello,

Fair enough!

Would like to thank you once again for the upgrade)))
