### ISSUE TITLE
Check if filetype/link is openable

### ISSUE THREAD

**Issue by kizaski** [RussCoder/djvujs#85]
My suggestion is to return the home page with an error message when an unreadable link and file (the file type is different than djvu) is given

**Comment by RussCoder** [comment]
As I see now, there is no message at all. Just an error in the console. 
It's not good - I thought there is a message. I will definitely add it, but I don't think the idea to close the current document and return to the initial screen will improve user experience. However, I think this error mostly happens on the initial screen when no document is open and a user drags & drops a file.

**Comment by RussCoder** [comment]
Fixed in the latest release (viewer v.0.9.1)
