### ISSUE TITLE
Tailwind preflight

### ISSUE THREAD

**Issue by slavonika** [RussCoder/djvujs#88]
При использовании css-фреймворка tailwind внешний вид интерфейса может быть искажен.

![image](https://github.com/RussCoder/djvujs/assets/7840979/470397a9-54e3-41de-b24f-67cee9f79cd3)

Предполагается, что tailwind производит сброс стилей по умолчанию, которые затем явно не прописаны в компоненте djvujs.

https://tailwindcss.ru/docs/preflight/

**Comment by RussCoder** [comment]
Помимо сброса стилей он ещё их и меняет. В частности `svg { display: block }` ломает верстку, как видно на скриншоте - иконки над текстом. 

Но я нашел способ сбросить эти глобальные стили. Будет включено в следующий релиз.

**Comment by slavonika** [comment]
Могу я поинтересоваться, запланированы ли в ближайшее время ближайшие релизы?)

**Comment by RussCoder** [comment]
Да, постараюсь в течение пары недель выпустить новую версию.

**Comment by RussCoder** [comment]
Готово. Исправлено в последней версии DjVu.js Viewer: `0.10.0`.

**Comment by slavonika** [comment]
> Готово. Исправлено в последней версии DjVu.js Viewer: `0.10.0`.

От всей души благодарим. Работает!
