### ISSUE TITLE
FireFox Problem

### ISSUE THREAD

**Issue by daa2018** [RussCoder/djvujs#9]
Обнаружено, что странички на mk-archive.narod.ru не открываются, так как плагин каминовы на свежий ФФ не ставится. Просьба сделать новый плагин для кода:
`<EMBED TYPE="image/x-djvu" SRC="jmk651201.djv" WIDTH="950" HEIGHT="82%"></EMBED>`

Сейчас, чтобы открыть странички на mk-archive, пришлось поставить отдельный ФФ 3.6.28.

**Comment by RussCoder** [comment]
Здравствуйте!
Хочу уточнить пару моментов:
- Что такое "плагин каминовы"?
- Вы хотите чтобы я сам сделал новый плагин, который бы заменял теги типа 
`<EMBED TYPE="image/x-djvu" SRC="jmk651201.djv" WIDTH="950" HEIGHT="82%"></EMBED>`
на DjVu.js Viewer?

**Comment by RussCoder** [comment]
Хорошо, я попробую это сделать. Как сделаю (или сочту, что игра не стоит свеч), напишу тут.

**Comment by RussCoder** [comment]
Мне это удалось. Посмотрите, если все ок, то закрываете issue, иначе - пишите пожелания. 
![image](https://user-images.githubusercontent.com/18438165/41527579-47079de4-72f0-11e8-80e0-743114a1e1b1.png)
