### ISSUE TITLE
I can't install the DjVu Extension for Chrome from the Chrome Web Store

### ISSUE THREAD

**Issue by DavidAntoFrost** [RussCoder/djvujs#93]
See the attached images.
When I try to install the DjVu Extension from Chrome, I get a strange message (It can: Read and change all your data on all websites) and I can't proceed with the installation.  Any idea what is going on?

![image](https://github.com/RussCoder/djvujs/assets/24961139/454137ac-9555-4b6a-af15-1633e82ea258)

![image](https://github.com/RussCoder/djvujs/assets/24961139/dbe397a0-d832-44f0-b5a3-8b72d8052c0e)

Thanks in advance.
D.

**Comment by RussCoder** [comment]
As for the message, it was always there. As it's said in the description: "It requires access to third-party websites only to render embedded documents (<embed> tag) and open links to .djvu files (on any website)". 

As for the "Download error", I have no idea why it happens and what Google did with the extension. I republished the same version, but it didn't help. Now maybe I will publish a new version with no changes. 

That is, it's completely a Chrome Web Store issue. Maybe I will send them a message.

**Comment by DavidAntoFrost** [comment]
Many thanks for the prompt reply.

Regards,
David.

**Comment by DavidAntoFrost** [comment]
Dear RussCoder,

Many thanks for sorting out the issue with the DjVu Extension in the Chrome Web Store.

I can now download and install the DjVu Extension for Chrome.

Regards,
David.

From: David Frost
Sent: Friday, February 9, 2024 4:18 PM
To: RussCoder/djvujs ***@***.***>; RussCoder/djvujs ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [RussCoder/djvujs] I can't install the DjVu Extension for Chrome from the Chrome Web Store (Issue #93)

Many thanks for the prompt reply.

Regards,
David.

**Comment by RussCoder** [comment]
Hello. You are welcome. I fixed it having published a new version with no changes. 
P.S.: Do you understand that it's not an email, but a message on GitHub in the issue you have opened? If you reply via email, your email is posted on GitHub.
